nav:
  - Overview: index.md
  - Getting started: getting-started.md
  - Tutorial:
    - Defining a document: tutorial/defining-a-document.md
    - Initialization: tutorial/init.md
    - Inserting into the database: tutorial/insert.md
    - Finding documents: tutorial/find.md
    - Lazy parsing: tutorial/lazy_parse.md
    - Updating & Deleting: tutorial/update_and_delete.md
    - Indexes: tutorial/indexes.md
    - Multi-model pattern: tutorial/multi-model.md
    - Inheritance: tutorial/inheritance.md
    - Aggregation: tutorial/aggregate.md
    - Relations: tutorial/relations.md
    - Views: tutorial/views.md
    - Time Series: tutorial/time_series.md
    - Event-based actions: tutorial/actions.md
    - Cache: tutorial/cache.md
    - Revision: tutorial/revision.md
    - State Management: tutorial/state_management.md
    - On save validation: tutorial/on_save_validation.md
    - Migrations: tutorial/migrations.md
  - Batteries:
    - Queue: batteries/queue.md
  - API Documentation:
    - Document: api-documentation/document.md
    - Union Document: api-documentation/union-document.md
    - Query: api-documentation/query.md
    - Interfaces: api-documentation/interfaces.md
    - Operators:
      - Find: api-documentation/operators/find.md
      - Update: api-documentation/operators/update.md
    - Fields: api-documentation/fields.md
  - Development: development.md
  - Code of conduct: code-of-conduct.md
  - Changelog: changelog.md

site_name: Beanie Documentation
repo_url: https://github.com/BeanieODM/beanie
site_url: https://beanie-odm.dev/
docs_dir: docs
extra_css:
  - assets/stylesheets/color_scheme.css
  - assets/stylesheets/custom.css
watch:
  - beanie
  - docs
  - mkdocs.yml
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
theme:
  favicon: assets/favicon.png
  logo: assets/logo.svg
  name: material
  palette:
    - primary: white
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.instant
    - toc.follow
    - search.highlight
    - content.code.copy
    - content.tabs.link
plugins:
  - search
  - autorefs
  - mkdocstrings:
      enable_inventory: false
      custom_templates: docs/templates
      default_handler: python
      handlers:
        python:
          options:
            # Headings
            show_root_heading: true
            show_root_toc_entry: true
            show_object_full_path: false
            show_category_heading: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_members_full_path: true

            # Class
            show_bases: true

            # Members
            members_order: source
            group_by_category: false
            show_submodules: true

            # Docstrings
            docstring_style: sphinx # reStructuredText
            docstring_section_style: list
            merge_init_into_class: false
            show_if_no_docstring: false # if true, shows all possible variables/attributes
            show_docstring_description: true
            show_docstring_attributes: true
            show_docstring_examples: true
            show_docstring_classes: false
            show_docstring_modules: false

            # Signatures
            show_signature: true
            show_signature_annotations: true
            separate_signature: true
            line_length: 80

            # Filters
            filters: ["!^_"]
            inherited_members: true
